### ISSUE TITLE
Unable to download documents on Staging site

### ISSUE THREAD

**Issue by jahnvidave** [IATI/preview-website#145]
Hi,

Not able to download documents (pdf and csv), when testing the staging site of the 'About' section.

I have tried in both Chrome and Explorer.

See for example:
Annual Reports: http://staging2.iatistandard.org/en/about/governance/annual-reports/
Governance: http://staging2.iatistandard.org/en/about/governance/

Clicking on the documents should download them. And this works on the alpha version.

But on the staging version, when you click on a document the webpage reloads and the document does not download.

Thanks,
Jahnvi

**Comment by akmiller01** [comment]
Resolved in https://github.com/IATI/preview-website/pull/144
