### ISSUE TITLE
Home: Statistic digit jumps down in Firefox

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/preview-website#175]
On Firefox 60, but not 59. When the breakpoint is > 1280, the last digit jumps a line

<img width="1095" alt="screen shot 2018-07-02 at 15 03 28" src="https://user-images.githubusercontent.com/8557782/42230774-bed4d236-7ee1-11e8-9794-5460dda80e6e.png">

**Comment by Daviniafffunction** [comment]
Moved to the PL repo: https://github.com/IATI/IATI-Pattern-Library/issues/95
