### ISSUE TITLE
Captions return None if no data is present for the field

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/preview-website#178]
See here: https://iatistandard.org/en/iati-standard/

<img width="670" alt="screen shot 2018-07-03 at 17 01 09" src="https://user-images.githubusercontent.com/8557782/42231162-b6a684a0-7ee2-11e8-9091-48e2f9ed64e5.png">

Should there be a fallback if no data is entered, or not appear at all?

**Comment by allthatilk** [comment]
This issue has been fixed. Closing.

**Comment by andylolz** [comment]
In 4a0e1beb, I think.
