### ISSUE TITLE
T1.1 About subpage  template design

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#18]
Design for this page is here: http://iati.surge.sh/page-templates/01-1-about-subpage

The model for the page would be something like: 

* title
* content_editor

The members assembly block in the sidebar is an optional item, the model for which should be something like: 

* block_title
* block_content
* block_button_text
* block_button_url

From Trello card: https://trello.com/c/9lCcuVpq/82-t11-about-subpage-template-design

**Comment by benjamincoleman** [comment]
@dalepotter @allthatilk @akmiller01 we now have guidance on the submenu design when it's at a couple of layers deep: http://iati.surge.sh/page-templates/01-1b-about-subpage-3-levels

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
