### ISSUE TITLE
JS error on homepage and throughout

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/preview-website#180]
```
basicScroll JS errors (Uncaught TypeError: Cannot read property 'track' of null)
```

<img width="1806" alt="screen shot 2018-07-02 at 15 59 27" src="https://user-images.githubusercontent.com/8557782/42231297-1aedfd4e-7ee3-11e8-91cb-cea0890ab175.png">

**Comment by sargentfrancesca** [comment]
@BenDarby @benjamincoleman

**Comment by allthatilk** [comment]
This one needs a status update as I can't see them on the live site:
![screen shot 2018-08-07 at 12 41 12](https://user-images.githubusercontent.com/23729009/43773916-31248750-9a3f-11e8-8369-d95db8106329.png)

**Comment by Daviniafffunction** [comment]
Moved to the PL repo: https://github.com/IATI/IATI-Pattern-Library/issues/92
