### ISSUE TITLE
Guidance Page: 'Contact Support' missing from a child page

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/preview-website#183]
Should 'contact support' appear on all guidance pages? this is the PL equiv https://iatistandard.org/en/guidance/preparing-data/what-data-to-publish/

**Comment by allthatilk** [comment]
@IATI/bas Any ideas on this question?

**Comment by amy-silcock** [comment]
@allthatilk can you explain further please. The 'contact support' is on the guidance pages....? Barr those which just have cards.

**Comment by Daviniafffunction** [comment]
Moved to the PL repo: https://github.com/IATI/IATI-Pattern-Library/issues/90
