### ISSUE TITLE
Guidance Page: Spacing on contact support form success seems off

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/preview-website#184]
<img width="784" alt="screen shot 2018-07-03 at 11 01 24" src="https://user-images.githubusercontent.com/8557782/42231779-6215eb4a-7ee4-11e8-96a1-6b7a11c57c1a.png">

A page that has this form: https://iatistandard.org/en/guidance/preparing-organisation/organisation-data-publication/key-qualities-of-iati-data/

**Comment by Daviniafffunction** [comment]
Moved to the PL repo: https://github.com/IATI/IATI-Pattern-Library/issues/87
