### ISSUE TITLE
News Page: Article text is too close to footer

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/preview-website#186]
https://iatistandard.org/en/news/promoting-iati-data-at-world-press-freedom-day/

<img width="1039" alt="screen shot 2018-07-03 at 15 04 37" src="https://user-images.githubusercontent.com/8557782/42231928-da072cf4-7ee4-11e8-8e1c-fd6de18eec26.png">

**Comment by Daviniafffunction** [comment]
Moved to the PL repo: https://github.com/IATI/IATI-Pattern-Library/issues/89
