### ISSUE TITLE
Typekit 403

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#189]
I'm seeing a 403 for Typekit CSS on live: 

`esn8rgw.css:1 Failed to load resource: the server responded with a status of 403 ()`

I think you need to check the domain is listed correctly in your Typekit account.

Here's a similar report and some support that will help:

https://forums.adobe.com/thread/1554778

**Comment by Daviniafffunction** [comment]
Moved to the PL repo: https://github.com/IATI/IATI-Pattern-Library/issues/88
