### ISSUE TITLE
T1.5 History page design

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#19]
Page design: http://iati.surge.sh/page-templates/01-5-history

Model would be something like: 

* title
* intro_text - a text area
* content_editor
* history list - where you can add multiple items, each item would have:
    * history_item_date (text field) - best keep as a text field rather than datetime for flexibility
    * history_item_content (text and links)

From Trello card: https://trello.com/c/b39taEKy/89-t15-history-page-design

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
