### ISSUE TITLE
T1.3 Download listing  template design

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#20]
Design in pattern library: http://iati.surge.sh/page-templates/01-3-download-listing

Same as the about sub page template, but we'd want the download element to be available for all about section pages.

For each download link the model is: 

* download_title
* download_url

You should then detect the file type and file size to show it automatically - ping Russell or Francesca if you want a code example of how we do this. 

From Trello card: https://trello.com/c/OdLTHJRF/77-t13-download-listing-template-design

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
