### ISSUE TITLE
Production site is deployed from an unmerged feature branch

### ISSUE THREAD

**Issue by andylolz** [IATI/preview-website#206]
## Problem

Presumably as a result of the surge to launch in time for the [Members’ Assembly](http://iatistandard.org/en/about/join-iati/members-assembly/), the new [IATI website](http://iatistandard.org) is currently deployed from [an unmerged feature branch](https://github.com/IATI/preview-website/pull/4) (`add-page-models`) instead of [the `master` branch](https://github.com/IATI/preview-website/tree/master). I guess this is okay, but it’s not really ideal.

Merging to `dev` and to `master` is blocked, because [linting checks fail](https://travis-ci.org/IATI/preview-website/builds/401705790).

## Proposed solution

I’ve sent the following pull requests to fix linting: #208, ~~#205~~, #204, #203, #201, #199 (these pull requests replace #55). Once all of these are reviewed and merged, it should be fine to merge #4 (`add-page-models` -> `dev`) and subsequently #22 (`dev` -> `master`).

**Comment by andylolz** [comment]
Fixed in #22!

**Comment by dalepotter** [comment]
Good to flag this @andylolz - was just going to say this can be closed once https://github.com/IATI/deployment/pull/49 is merged and a deployment is run!

**Comment by andylolz** [comment]
Hadn’t spotted that one! Totally agree. Reopening – I’ll leave it with you.

**Comment by andylolz** [comment]
I guess this can now be closed?
