### ISSUE TITLE
List d-portal as a Development Initiatives product, not an IATI product

### ISSUE THREAD

**Issue by andylolz** [IATI/preview-website#207]
The [IATI tools and resources page](http://iatistandard.org/en/using-data/IATI-tools-and-resources/) lists [d-portal](http://d-portal.org/) as an IATI product:
![screen shot 2018-07-15 at 21 27 48](https://user-images.githubusercontent.com/464193/42738089-f5c1f2e0-8875-11e8-8f4e-780919053040.png)

However, it was made clear at the [Members’ Assembly](http://iatistandard.org/en/about/join-iati/members-assembly/) that it is in fact a [Development Initiatives](http://devinit.org/) product. It was clear from Members’ Assembly discussions that there‘s some confusion around this, and therefore it’s important to make this distinction clear.

I suggest updating the [IATI tools and resources page](http://iatistandard.org/en/using-data/IATI-tools-and-resources/) accordingly.

@bill-anderson @PetyaKangalova please feel free to correct if I’ve got the wrong end of the stick here. I found Pin’s clarification on this very helpful, and it would be good if the website confirmed rather than contradicted her point.

/cc @PetyaKangalova @amy-silcock as a process point, I’m unsure whether this is the correct place to raise content issues for the new website?

**Comment by bill-anderson** [comment]
d-portal has indeed changed hands between DI and IATI in its history but is currently an IATI product. It was built by IATI for the first GPEDC meetiing and is currently maintained by IATI

**Comment by andylolz** [comment]
Okay so in that case the website is correct and I’ll close this. But this wasn’t my understanding, based on Pin’s comments at the MA.
