### ISSUE TITLE
Broken link in registry API documentation

### ISSUE THREAD

**Issue by andylolz** [IATI/preview-website#225]
I flagged this same issue when this documentation lived on the registry: https://github.com/IATI/ckanext-iati/pull/176

It has since been migrated to iatistandard.org:
https://iatistandard.org/en/using-data/IATI-tools-and-resources/using-IATI-registry/

…But the typo has been copied across.

It’s the bit that says “To fetch activity files:”

The anchor text is correct. But the href attribute is currently:
http://iatiregistry.org/api/3/action/package_search?q=extras_filetype:activity/%25s/iati2.staging.ckanhosted.com/iatiregistry.org/g/%25s/iati2.staging.ckanhosted.com/iatiregistry.org/g

It should instead be:
http://iatiregistry.org/api/3/action/package_search?q=extras_filetype:activity

@PetyaKangalova @amy-silcock are you able to fix this link via the CMS? Thanks!

**Comment by jahnvidave** [comment]
Great, thanks Andy. That's now been changed.

**Comment by andylolz** [comment]
Excellent! Thanks @jahnvidave.
