### ISSUE TITLE
Link to the CKAN API documentation is wrong

### ISSUE THREAD

**Issue by andylolz** [IATI/preview-website#239]
Originally flagged by @notshi.

On this page:
https://iatistandard.org/en/using-data/IATI-tools-and-resources/using-IATI-registry/

In the “Using the Registry metadata API” section, the link to the CKAN API documentation links to [the latest version of the CKAN API documentation](http://docs.ckan.org/en/latest/api/index.html) – currently 2.9.0a. That’s not the version running on the registry – it should instead link to:
http://docs.ckan.org/en/2.8/api/index.html

**Comment by Ocre42** [comment]
Sorted! thank you for pointing this out Andy
