### ISSUE TITLE
T5 Contact template design

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#24]
Design: http://iati.surge.sh/page-templates/05-contact

Model would be something like: 

* title
* intro (text area)
* content_editor
* contact_blocks with each contact block consisting of:
    * block_title (text field)
    * block_text (text area)
    * block_button_label (text field)
    * block_button_url (text field)

From Trello card: https://trello.com/c/xRnWGBDx/87-t5-contact-template-design

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
