### ISSUE TITLE
T0.0 News Archive

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#25]
Pattern library link: http://iati.surge.sh/page-templates/03-news

Shows a list of news posts in chronological order with the most recent appearing first. 

The first post in the list has a different style as indicated in the design

On pages 2, 3 etc. all posts in the list would have the same style. 

If you click on a category item it would take you to a category page template which would be very much like this page - we're still to do this page template though, and it's likely we'll do it in Sprint 4.

When creating the category taxonomy please have it so that a news item can only belong to one category.

From Trello card: https://trello.com/c/dfAYUPqH/43-t00-news-archive

**Comment by benjamincoleman** [comment]
http://iati.surge.sh/page-templates/03a-news-filtered

We now have a filtered state for the news page. 

Shows the title with the filtered state of the list, show all posts links back to the /news/ page and the filter sub menu should have an active state.

**Comment by benjamincoleman** [comment]
@dalepotter @allthatilk @akmiller01 See above comment for updated design for filtered state https://github.com/IATI/preview-website/issues/25#issuecomment-384075958

**Comment by akmiller01** [comment]
@allthatilk re-reading this issue, I need to query the page number for NewsIndexPage and re-style the first item on pages greater than 1.

**Comment by akmiller01** [comment]
@allthatilk Just https://github.com/IATI/preview-website/pull/137 and then we can close this issue.
