### ISSUE TITLE
T0.0 News Single

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#26]
Template design: http://iati.surge.sh/page-templates/03-1-news-single

Shows a single news item. Model would be something like: 

* title
* publish_date
* content_editor
* related_content (relationship)

The logic we generally use here is that you can either nominate 1 or 2 posts / pages which are then shown, or it fills up with the latest news content from the same blog category as this post.

From Trello card: https://trello.com/c/r5eSa8Mf/44-t00-news-single

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
