### ISSUE TITLE
T1.0 About IATI  template design

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#27]
http://iati.surge.sh/page-templates/01-

About section heading page - used for P1.0 About IATI

Model would be something like: 

* title
* intro (text area)
* content_editor

The members assembly block in the sidebar is an optional item, the model for which should be something like:

* block_title
* block_content
* block_button_text
* block_button_url

This block appears on several templates

From Trello card: https://trello.com/c/NfUCLeUt/78-t10-about-iati-template-design

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
