### ISSUE TITLE
T4.1 Event single  template design

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#28]
Design is here: http://iati.surge.sh/page-templates/04-1-events-single

Model would be something like: 

* title
* image (image)
* intro (textarea)
* event_type (taxonomy)
* event_location (textarea)
* event_start_date (datetime)
* event_end_date (datetime)
* event_start_time (datetime)
* event_end_time (datetime)
* event_register_url (url)
* event_eventbrite_id (textfield) e.g. 33395177876 see below for implementation code
* content_editor 
* info_box_title (textfield)
* info_box_content (content_editor)
* downloads - for each download link the model is: 
    * download_title
    * download_url

---

A single event should have the following:

- an image
- event title
- event date - can have the format of 4th - 9th April as some events are multiple days
- event times - e.g. 9am - 5pm
- event location
- event content - editor content describing what is going on
- button to link to event registration
- eventbrite embed (see http://asdc.surge.sh/page-templates/5-1-event for example, I'll paste the code in below
- additional info box for info like accomodation etc. 

Possible example event: https://discuss.iatistandard.org/t/minitag-on-friday-29th-washington-dc/1030

```
<div id="eventbrite-widget-container-33395177876"></div>
<script src="https://www.eventbrite.co.uk/static/widgets/eb_widgets.js"></script>
<script type="text/javascript">
    var exampleCallback = function() {
        console.log('Order complete!');
    };
    window.EBWidgets.createWidget({
        // Required
        widgetType: 'checkout',
        eventId: '33395177876',
        iframeContainerId: 'eventbrite-widget-container-33395177876',
        // Optional
        iframeContainerHeight: 425,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
    });
</script>
```

From Trello card: https://trello.com/c/drEzt1W2/79-t41-event-single-template-design

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
