### ISSUE TITLE
T4.0a Past events  template design

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#29]
Design is here: http://iati.surge.sh/page-templates/04a-past-events

Shows past events. This is a very close variation of this template: https://trello.com/c/kp7pnZPT and so has the same model / functionality / categorisation. 

From Trello card: https://trello.com/c/yprKQqtm/85-t40a-past-events-template-design

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
