### ISSUE TITLE
T4.1a Past event single  template design

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#30]
Template design ready: http://iati.surge.sh/page-templates/04-1a-past-events-single

Model is identical to the events single template

---

A variation of https://trello.com/c/drEzt1W2 but this event has passed so:

- don't show any links / calls to action around signing up or registration
- the event will now be used to tell people what happened there so the content will be longer and broken up into sections with titles.

From Trello card: https://trello.com/c/MVuM8dYB/86-t41a-past-event-single-template-design

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
