### ISSUE TITLE
T1.4b Past Event Members Assembly

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#31]
http://iati.surge.sh/page-templates/04-1b-past-events-single

Variation of past event for the members assembly, spawned from this card: https://trello.com/c/MVuM8dYB

Will have same model as event single template

From Trello card: https://trello.com/c/8DiXe676/99-t14b-past-event-members-assembly

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
