### ISSUE TITLE
T4.0 Events  

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#32]
Design ready: http://iati.surge.sh/page-templates/04-events

Model:

* title
* intro (textarea)
* image (image)

The template also lists the event_type taxonomy

The template also lists events in chronological order, the next event first. 

---

Page purpose: Provide information on events
Content goal:  Show events run by IATI / partners

Should show a list of events in order of date.

For each event listing show: 

- an image
- event title
- event date - can have the format of 4th - 9th April as some events are multiple days
- event location
- event description

More details on events in the single card here > https://trello.com/c/drEzt1W2

From Trello card: https://trello.com/c/kp7pnZPT/84-t40-events-template-design

**Comment by benjamincoleman** [comment]
@akmiller01 @dalepotter @allthatilk We now have a filtered state for this template design: http://iati.surge.sh/page-templates/04a-events-filtered

Additional items are the title showing what the list of events is filtered by, the "show all events" link which links page to the main events page, and the active state of the event filter menu

**Comment by benjamincoleman** [comment]
@allthatilk @akmiller01 @dalepotter We now have a placeholder image to use if there is not an image available for an event: http://iati.surge.sh/page-templates/04a-events-filtered

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
