### ISSUE TITLE
T1.2 Case studies

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#33]
http://iati.surge.sh/page-templates/01-2-case-studies

Lists the case studies on the site

Model:

* title
* intro (textarea)
* image (image)

Then has the submenu from the about section, as this page is in the about section. 

Then lists the case studies we have

From Trello card: https://trello.com/c/iEcnUu5g/98-t12-case-studies

**Comment by allthatilk** [comment]
@akmiller01 have we implemented this placeholder? I know there's still a card for placeholder images in Trello so want to check and see if this still relevant or can be closed =)

**Comment by akmiller01** [comment]
Yep
