### ISSUE TITLE
T1.2.1 Case study template design

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#36]
Design ready: http://iati.surge.sh/page-templates/01-2-1-case-study

Model would be something like: 

* title
* intro (textarea)
* image (image)
* outcomes_title (text field)
* outcomes_content (content_editor)
* outcomes_image (image)
* outcomes_image_caption (text field)
* process_title (text field)
* process_content (content_editor)
* quote_image (image)
* quote_content (textarea)
* quote_source (text field)
* stats (repeater)
    * stat_title (text field)
    * stat_content (text field)
* downloads (repeater)
    * download_title (text field)
    * download_url (url)

The download module will exist throughout the about section page templates

From Trello card: https://trello.com/c/ikB1Bo65/80-t121-case-study-template-design

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
