### ISSUE TITLE
Locale trying to append gb

### ISSUE THREAD

**Issue by akmiller01** [IATI/preview-website#60]
Hey @allthatilk ,

For some reason, my development server started re-directing links to en-gb when I clicked "Live" in the admin panel. E.g. http://localhost:8000/en-gb/events

I'm guessing this is due to our localization settings in base.py.

**Comment by allthatilk** [comment]
Yep, that's going to be why. Can we just set it to a generic `en`?

**Comment by akmiller01** [comment]
Fix with https://github.com/IATI/preview-website/pull/64
