### ISSUE TITLE
Home/site disassociation

### ISSUE THREAD

**Issue by akmiller01** [IATI/preview-website#72]
Some step in our latest deployment (https://github.com/IATI/deployment/pull/31) process causes the Home page to become disassociated with the `site` object. This can be remedied by clicking on the warning in the CMS, selecting the site, and hitting save, but we should figure out what step is causing it.

It's also a pretty major problem since it causes all of the pages to return "None" for their urls, which breaks all of the links.

I'm going to blame migrations on this one, somehow, @allthatilk! It's possible it might be something that sorts itself out when we stop ignoring migrations. Or we could throw out migration `home/0002_create_homepage.py` and instead create the homepage via createdefaultpages, thus ensuring it's always properly attached to the site root.

**Comment by allthatilk** [comment]
@akmiller01 Is this one still causing problems or can we close?

**Comment by akmiller01** [comment]
We can close it. Fixed when createdefaultpages became idempotent
