### ISSUE TITLE
T2.0a - Guidance and support section interim page

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#74]
http://iati.surge.sh/page-templates/02a-guidance-support 

This is the head page for the Guidance and Support section. 

It will eventually be replaced by https://trello.com/c/i8w4TsyOa nd https://trello.com/c/3UF3nVNA

This page has the following model:

- title
- intro
- sub title
- content (rich text)

This page then lists its immediate subpages as three main blocks of content each comprising of:

- Title
- Image
- Summary (rich text)
- Button label

We'd probably build this out to pull in all the content from each subpage.

---

This is an interim page for the Guidance section. 

Should have the image hero variant we use for section headings and the model would be something like this:

* title
* intro (textarea)
* image (image)
* content_editor

Then the template shows the sections below it, which in this case are shown in the sketch.

When we have the Knowledge Base created and maybe the Data Guide then this page will be replaced with https://trello.com/c/i8w4TsyO and the content moved to this template: https://trello.com/c/3UF3nVNA

From Trello card: https://trello.com/c/4CiCC8qh/119-t20a-guidance-and-support-section-interim-page

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
