### ISSUE TITLE
T2.2 - Guidance section e.g. Preparing your organisation

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/preview-website#79]
http://iati.surge.sh/page-templates/02-2-guidance-section 

This template shows an array of cards for the pages immediately beneath it. 

If the page represented by a card has children then it has an alternate design which should indicate multiple pages - hence the stacked pages in the sketch. The number of pages immediately underneath is also indicated.

This template also introduced a breadcrumb, which starts with the guide it is in, so the root here would be "IATI Publishers Guide" >  "Preparing your data" 

From Trello card: https://trello.com/c/butXEHq4/113-t22-guidance-section-eg-preparing-your-organisation

**Comment by allthatilk** [comment]
Now implemented. Closing issue.
